export const permissionKeys = [
  'admin.dashboard.view',
  'accounts.view',
  'accounts.create',
  'accounts.modify',
  'accounts.suspend',
  'accounts.terminate',
  'accounts.password',
  'packages.manage',
  'resellers.manage',
  'domains.manage',
  'dns.manage',
  'email.manage',
  'databases.manage',
  'files.manage',
  'ssl.manage',
  'backups.manage',
  'security.view',
  'security.manage',
  'services.manage',
  'server.configure',
  'metrics.view',
  'audit.view',
  'api_tokens.manage',
  'users.manage',
  'roles.manage'
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const defaultRolePermissions: Record<string, PermissionKey[]> = {
  super_admin: [...permissionKeys],
  server_admin: [
    'admin.dashboard.view',
    'accounts.view',
    'accounts.create',
    'accounts.modify',
    'accounts.suspend',
    'accounts.terminate',
    'accounts.password',
    'packages.manage',
    'resellers.manage',
    'domains.manage',
    'dns.manage',
    'email.manage',
    'databases.manage',
    'files.manage',
    'ssl.manage',
    'backups.manage',
    'security.view',
    'security.manage',
    'services.manage',
    'server.configure',
    'metrics.view',
    'audit.view',
    'api_tokens.manage',
    'users.manage',
    'roles.manage'
  ],
  reseller: [
    'admin.dashboard.view',
    'accounts.view',
    'accounts.create',
    'accounts.modify',
    'accounts.suspend',
    'accounts.password',
    'domains.manage',
    'dns.manage',
    'email.manage',
    'databases.manage',
    'files.manage',
    'ssl.manage',
    'backups.manage',
    'metrics.view',
    'api_tokens.manage'
  ],
  account_owner: [
    'accounts.view',
    'accounts.password',
    'domains.manage',
    'dns.manage',
    'email.manage',
    'databases.manage',
    'files.manage',
    'ssl.manage',
    'backups.manage',
    'metrics.view',
    'api_tokens.manage'
  ],
  team_member: [
    'accounts.view',
    'domains.manage',
    'dns.manage',
    'email.manage',
    'databases.manage',
    'files.manage',
    'ssl.manage',
    'backups.manage',
    'metrics.view'
  ],
  read_only: [
    'admin.dashboard.view',
    'accounts.view',
    'metrics.view',
    'audit.view'
  ]
};
